apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: workshop-springboot-hello_by_lang
  title: Hello Spring Boot
  description: |
    Introduction to Red Hat Dev Spaces with a Spring Boot translation service
  annotations:
    backstage.io/techdocs-ref: dir:.
#   backstage.io/techdocs-ref: dir:https://<hosted-git-repo>     # use absolute path instead to consolidate techdocs among repo forks
  tags:
    - devspaces
    - springboot
# links:
#   - url: https://<devspaces-url>/#<hosted-git-repo>
#     title: 🚀 Launch from Dev Spaces
#     icon: web
spec:
  type: module
  lifecycle: production
  owner: group:default/workshop-admins
  subcomponentOf: component:default/workshop-repository
