apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: workshop-springboot-hello_by_lang
  title: Hello Spring Boot
  description: |
    Introduction to Red Hat Dev Spaces with a Spring Boot translation service
  annotations:
    backstage.io/kubernetes-id: workshop-springboot-hello-by-lang
    backstage.io/kubernetes-namespace: developers-devspaces
    backstage.io/techdocs-ref: dir:.
#   backstage.io/techdocs-ref: dir:https://<hosted-git-repo>   # use absolute path instead to consolidate techdocs among repo forks
#   gitlab.com/instance: ""                                    # uncomment these two gitlab.com lines to disable GitLab tabs
#   gitlab.com/project-slug: ""                                # i.e. Issues, Pull/Merge Requests, CI in entity details
    janus-idp.io/tekton: workshop-springboot-hello-by-lang
  tags:
    - devspaces
    - springboot
# links:
#   - url: https://<devspaces-url>/#<hosted-git-repo>
#     title: 🚀 Launch from Dev Spaces
#     icon: web
spec:
  type: module
  lifecycle: development
  owner: group:default/workshop-admins
  subcomponentOf: component:default/workshop-repository
